---
# NOTE: groups 'all' and 'ungrouped' are Ansible default and thus always available!
#       For more info, see https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html

all:
  children:
