---
# NOTE: groups 'all' and 'ungrouped' are Ansible default and thus always available!
#       For more info, see https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html

all:
  children:
    proxmox:
      hosts:
        mto-pve01:
          ansible_host: 192.168.7.210
        mto-pve02:
          ansible_host: 192.168.7.220
        mto-pve03:
          ansible_host: 192.168.7.230
